import turtle as t
t.speed(10)
t.bgcolor("white")
t.pensize(5)
t.color("black","red")
t.left(90)
t.penup()
t.forward(200)
t.right(90)
t.pendown()
t.begin_fill()
t.circle(-150)
t.end_fill()
t.circle(-150,30)
t.right(130)
t.color("black","black")
t.begin_fill()
for i in range(30):
    t.forward(6)
    t.left(1)
t.right(85)
t.forward(74)
t.left(145)
for i in range(30):
    t.forward(6)
    t.left(1)
t.right(85)
t.forward(70)
t.left(145)
for i in range(30):

    t.forward(6)
    t.left(1)
t.right(85)
t.forward(70)
t.left(143)
for i in range(30):
    t.forward(6)
    t.left(1)
t.right(85)
t.forward(66)
t.end_fill()
t.color("red","red")
t.left(180)
t.penup()
t.forward(130)
t.right(45)
t.forward(15)
t.right(180)
t.forward(9)
t.begin_fill()
t.circle(-25)
t.end_fill()
 